version: '3.8'

services:
  app:
    build: .
    container_name: kit_global_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/kit_global_task
      - JWT_SECRET=your_super_secret_random_key_for_prod
      - JWT_EXPIRES_IN=24h
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: kit_global_database
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
